from datetime import UTC, datetime, timedelta


USERS = [
    {
        "id": "U01862",
        "discord_user_id": "discord-01862",
        "name": "Thái Hoài An",
        "member_label": "T004-Thái Hoài An-01862",
        "role": "student",
        "cohort_id": "K4",
        "team_id": "T004",
        "group_id": "G10",
        "lecture_room_id": "LEC-D302",
        "lab_room_id": "LAB-D304",
    },
    {
        "id": "U01823",
        "discord_user_id": "discord-01823",
        "name": "Nguyễn Đức Dũng",
        "member_label": "T004-Nguyễn Đức Dũng-01823",
        "role": "student",
        "cohort_id": "K4",
        "team_id": "T004",
        "group_id": "G10",
        "lecture_room_id": "LEC-D302",
        "lab_room_id": "LAB-D304",
    },
    {
        "id": "U01241",
        "discord_user_id": "discord-01241",
        "name": "Nguyễn Văn Phong",
        "member_label": "T004-Nguyễn Văn Phong-01241",
        "role": "student",
        "cohort_id": "K4",
        "team_id": "T004",
        "group_id": "G10",
        "lecture_room_id": "LEC-D302",
        "lab_room_id": "LAB-D304",
    },
    {
        "id": "U01777",
        "discord_user_id": "discord-01777",
        "name": "Lê Minh Châu",
        "member_label": "T004-Lê Minh Châu-01777",
        "role": "student",
        "cohort_id": "K4",
        "team_id": "T004",
        "group_id": "G10",
        "lecture_room_id": "LEC-D302",
        "lab_room_id": "LAB-D304",
    },
    {
        "id": "M-G10",
        "discord_user_id": "discord-mentor-g10",
        "name": "Mentor Vũ Nhật Cường",
        "member_label": "Mentor G10 · Vũ Nhật Cường",
        "role": "mentor",
        "cohort_id": "K4",
        "team_id": None,
        "group_id": "G10",
        "lecture_room_id": None,
        "lab_room_id": None,
    },
    {
        "id": "U09999",
        "discord_user_id": "discord-09999",
        "name": "Trần Mai Lan",
        "member_label": "T009-Trần Mai Lan-09999",
        "role": "student",
        "cohort_id": "K4",
        "team_id": "T009",
        "group_id": "G10",
        "lecture_room_id": "LEC-D303",
        "lab_room_id": "LAB-D305",
    },
]


CHANNELS = [
    {
        "id": "announcements",
        "discord_channel_id": "dc-announcements",
        "name": "thông-báo-chung",
        "category": "LỚP HỌC · KHÓA 4",
        "kind": "announcement",
        "scope_type": "cohort",
        "scope_id": "K4",
        "unread_count": 0,
    },
    {
        "id": "general",
        "discord_channel_id": "dc-general",
        "name": "💬-chung",
        "category": "CỘNG ĐỒNG",
        "kind": "common",
        "scope_type": "cohort",
        "scope_id": "K4",
        "unread_count": 4,
    },
    {
        "id": "qa",
        "discord_channel_id": "dc-qa",
        "name": "🙋-hỏi-đáp",
        "category": "CỘNG ĐỒNG",
        "kind": "qa",
        "scope_type": "cohort",
        "scope_id": "K4",
        "unread_count": 2,
    },
    {
        "id": "sharing",
        "discord_channel_id": "dc-sharing",
        "name": "🏆-chia-sẻ",
        "category": "CỘNG ĐỒNG",
        "kind": "share",
        "scope_type": "cohort",
        "scope_id": "K4",
        "unread_count": 8,
    },
    {
        "id": "lecture-d302",
        "discord_channel_id": "dc-lec-d302",
        "name": "Lec-D302",
        "category": "LÝ THUYẾT",
        "kind": "lecture",
        "scope_type": "room",
        "scope_id": "LEC-D302",
        "unread_count": 1,
    },
    {
        "id": "lab-d304",
        "discord_channel_id": "dc-lab-d304",
        "name": "Lab-D304",
        "category": "THỰC HÀNH",
        "kind": "lab",
        "scope_type": "room",
        "scope_id": "LAB-D304",
        "unread_count": 3,
    },
    {
        "id": "group-g10",
        "discord_channel_id": "dc-group-g10",
        "name": "thảo-luận-G10",
        "category": "G-10 · MENTOR",
        "kind": "group",
        "scope_type": "group",
        "scope_id": "G10",
        "unread_count": 1,
    },
    {
        "id": "team-t004",
        "discord_channel_id": "dc-team-t004",
        "name": "t-004",
        "category": "TEAM PROJECT",
        "kind": "team",
        "scope_type": "team",
        "scope_id": "T004",
        "unread_count": 6,
    },
    {
        "id": "team-t009",
        "discord_channel_id": "dc-team-t009",
        "name": "t-009",
        "category": "TEAM PROJECT",
        "kind": "team",
        "scope_type": "team",
        "scope_id": "T009",
        "unread_count": 0,
    },
    {
        "id": "bot-commands",
        "discord_channel_id": "dc-bot",
        "name": "🤖-gõ-commands",
        "category": "BOT & TIỆN ÍCH",
        "kind": "common",
        "scope_type": "cohort",
        "scope_id": "K4",
        "unread_count": 0,
    },
]


def now_iso() -> str:
    return datetime.now(UTC).isoformat()


def _timestamp(*, days: int = 0, hours: int = 0, minutes: int = 0) -> str:
    moment = datetime.now(UTC).replace(second=0, microsecond=0)
    moment += timedelta(days=days, hours=hours, minutes=minutes)
    return moment.isoformat()


def _message(
    identifier: str,
    channel_id: str,
    author_id: str,
    author_name: str,
    content: str,
    *,
    days: int = 0,
    hours: int = 0,
    minutes: int = 0,
) -> dict:
    return {
        "id": identifier,
        "source_message_id": identifier,
        "channel_id": channel_id,
        "author_id": author_id,
        "author_name": author_name,
        "content": content,
        "created_at": _timestamp(days=days, hours=hours, minutes=minutes),
        "permalink": f"https://discord.com/channels/demo-k4/{channel_id}/{identifier}",
        "source": "demo",
    }


def initial_state() -> dict:
    now = now_iso()
    discord_messages = [
        _message(
            "dc-msg-101",
            "general",
            "U01823",
            "T004-Nguyễn Đức Dũng-01823",
            "Mình đã tạo repo cho project, cả nhóm có thể vào làm việc rồi nhé.",
            days=-1,
            hours=-3,
        ),
        _message(
            "dc-msg-102",
            "general",
            "U01241",
            "T004-Nguyễn Văn Phong-01241",
            "Tối nay mình sẽ setup project. Mình cần chốt luôn nền tảng tóm tắt Discord.",
            days=-1,
            hours=-2,
        ),
        _message(
            "dc-msg-103",
            "general",
            "U01777",
            "T004-Lê Minh Châu-01777",
            "Mọi người nhớ đọc requirement pitching, vòng công bố vào thứ Sáu.",
            hours=-2,
        ),
        _message(
            "dc-msg-104",
            "general",
            "U01862",
            "T004-Thái Hoài An-01862",
            "Hackathon tính xây sản phẩm luôn. Team mình sẽ tận dụng project để test insight.",
            hours=-1,
        ),
        _message(
            "dc-msg-201",
            "lecture-d302",
            "M-G10",
            "Giảng viên · Lec-D302",
            "Bài hôm qua: bắt đầu từ pain point có bằng chứng, xác định user workflow rồi mới chốt feature.",
            days=-1,
            hours=-4,
        ),
        _message(
            "dc-msg-202",
            "lecture-d302",
            "M-G10",
            "Giảng viên · Lec-D302",
            "MVP cần một happy path chạy xuyên suốt, có dữ liệu demo và tiêu chí đánh giá cụ thể.",
            days=-1,
            hours=-3,
        ),
        _message(
            "dc-msg-203",
            "lecture-d302",
            "M-G10",
            "Giảng viên · Lec-D302",
            "Khi dùng AI, câu trả lời phải chỉ ra nguồn và nêu rõ phần nào là suy luận.",
            days=-1,
            hours=-2,
        ),
        _message(
            "dc-msg-301",
            "lab-d304",
            "M-G10",
            "TA · Lab-D304",
            "Lab hôm nay ưu tiên dựng API contract trước, sau đó mới nối UI và model.",
            hours=-3,
        ),
        _message(
            "dc-msg-401",
            "team-t004",
            "U01823",
            "T004-Nguyễn Đức Dũng-01823",
            "Repo chính là github.com/team-t004/discord-copilot. Dũng giữ backend và Docker.",
            hours=-5,
        ),
        _message(
            "dc-msg-402",
            "team-t004",
            "U01241",
            "T004-Nguyễn Văn Phong-01241",
            "Team chốt demo tính năng memory trước 18h hôm nay; stack giữ Next.js, FastAPI và Docker.",
            hours=-4,
        ),
        _message(
            "dc-msg-403",
            "team-t004",
            "U01777",
            "T004-Lê Minh Châu-01777",
            "Châu làm pitch flow và chuẩn bị ba câu hỏi demo cho ban giám khảo.",
            hours=-3,
        ),
        _message(
            "dc-msg-404",
            "team-t004",
            "U01862",
            "T004-Thái Hoài An-01862",
            "An phụ trách hoàn thiện API ingest và kiểm tra không lẫn dữ liệu giữa các team.",
            hours=-2,
        ),
        _message(
            "dc-msg-405",
            "team-t004",
            "U01241",
            "T004-Nguyễn Văn Phong-01241",
            "Blocker hiện tại: chưa map được channel Lab-D304 từ Apify dataset.",
            hours=-1,
        ),
        _message(
            "dc-msg-501",
            "group-g10",
            "M-G10",
            "Mentor Vũ Nhật Cường",
            "Mentor yêu cầu chuẩn bị bản demo và đẩy repo trước buổi check-in thứ Tư.",
            hours=-6,
        ),
        _message(
            "dc-msg-502",
            "group-g10",
            "M-G10",
            "Mentor Vũ Nhật Cường",
            "Phần pitch nên chứng minh một pain point thật từ Discord và cách đo giảm tải cho mentor.",
            hours=-5,
        ),
        _message(
            "dc-msg-601",
            "qa",
            "U09999",
            "T009-Trần Mai Lan-09999",
            "Các nhóm có cần deploy public trước vòng pitching không ạ?",
            hours=-4,
        ),
        _message(
            "dc-msg-701",
            "team-t009",
            "U09999",
            "T009-Trần Mai Lan-09999",
            "T009 chốt làm AI quiz generator và dùng Supabase.",
            hours=-2,
        ),
    ]

    return {
        "discord_messages": discord_messages,
        "memories": [
            {
                "id": "mem-user-an-style",
                "scope_type": "user",
                "scope_id": "U01862",
                "kind": "preference",
                "content": "An muốn nhận bản tóm tắt theo checklist, ưu tiên việc có deadline.",
                "evidence": ["dc-msg-404"],
                "created_by": "U01862",
                "status": "confirmed",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "mem-team-t004-stack",
                "scope_type": "team",
                "scope_id": "T004",
                "kind": "decision",
                "content": "T004 chốt demo memory trước 18h, dùng Next.js, FastAPI và Docker.",
                "evidence": ["dc-msg-402"],
                "created_by": "U01241",
                "status": "confirmed",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "mem-team-t004-blocker",
                "scope_type": "team",
                "scope_id": "T004",
                "kind": "blocker",
                "content": "T004 chưa map được channel Lab-D304 từ Apify dataset.",
                "evidence": ["dc-msg-405"],
                "created_by": "U01241",
                "status": "confirmed",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "mem-group-g10-checkin",
                "scope_type": "group",
                "scope_id": "G10",
                "kind": "task",
                "content": "Mentor yêu cầu chuẩn bị bản demo và đẩy repo trước check-in thứ Tư.",
                "evidence": ["dc-msg-501"],
                "created_by": "M-G10",
                "status": "confirmed",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "mem-room-d302-lesson",
                "scope_type": "room",
                "scope_id": "LEC-D302",
                "kind": "learning_note",
                "content": "MVP cần đi từ pain point có bằng chứng đến một happy path có tiêu chí đo.",
                "evidence": ["dc-msg-201", "dc-msg-202"],
                "created_by": "M-G10",
                "status": "confirmed",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "mem-team-t009-private",
                "scope_type": "team",
                "scope_id": "T009",
                "kind": "decision",
                "content": "T009 làm AI quiz generator và dùng Supabase.",
                "evidence": ["dc-msg-701"],
                "created_by": "U09999",
                "status": "confirmed",
                "created_at": now,
                "updated_at": now,
            },
        ],
        "candidates": [],
        "assistant_messages": {
            "U01862": [
                {
                    "id": "seed-assistant-an",
                    "role": "assistant",
                    "author_name": "Trợ lý Kute",
                    "content": (
                        "Chào An. Khi quay lại sau một ngày, bấm “Bắt kịp 24 giờ qua” để xem "
                        "quyết định, việc cần làm, deadline và blocker từ đúng các kênh bạn được phép đọc."
                    ),
                    "citations": [],
                    "memory_used": ["mem-user-an-style", "mem-team-t004-stack"],
                    "created_at": now,
                }
            ]
        },
        "ingestion": {
            "mode": "demo-snapshot",
            "dataset_id": None,
            "last_synced_at": None,
            "imported_count": len(discord_messages),
            "skipped_count": 0,
        },
        "catchup_briefs": {},
        "checklists": {},
        "acknowledged_briefs": {},
    }
